# Generated by Django 4.2.11 on 2024-04-05 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_alter_coach_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyms', '0002_alter_gym_options_alter_gym_email'),
        ('schedules', '0003_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-start_time', 'client__last_name', 'client__first_name'], 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AlterField(
            model_name='record',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_records', to='coaches.coach'),
        ),
        migrations.AlterField(
            model_name='record',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_records', to='gyms.gym'),
        ),
    ]
