# Generated by Django 4.2.11 on 2024-04-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
    ]
