# Generated by Django 4.2.11 on 2024-04-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('coach', 'Coach'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
