# Generated by Django 4.2.11 on 2024-04-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ['name'], 'verbose_name': 'Gym', 'verbose_name_plural': 'Gyms'},
        ),
        migrations.AlterField(
            model_name='gym',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
